apiVersion: v1
kind: Pod
metadata:
  name: cmdemo-image-recognition-worker
spec:
  containers:
  - name: cmdemo-worker 
    image: cvugrinec/image-recognition
    env:
      - name: CONTAINER_NAME 
        valueFrom:
          secretKeyRef:
            name: cmdemo-secrets
            key: CONTAINER_NAME
      - name: ACCOUNT_KEY
        valueFrom:
          secretKeyRef:
            name: cmdemo-secrets
            key: ACCOUNT_KEY
      - name: ACCOUNT_NAME
        valueFrom:
          secretKeyRef:
            name: cmdemo-secrets
            key: ACCOUNT_NAME
      - name: SP_NAME
        valueFrom:
          secretKeyRef:
            name: cmdemo-secrets 
            key: SP_NAME
      - name: SP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: cmdemo-secrets
            key: SP_PASSWORD
      - name: SP_TENANT
        valueFrom:
          secretKeyRef:
            name: cmdemo-secrets
            key: SP_TENANT

  restartPolicy: Never
