apiVersion: v1
kind: Secret
metadata:
    name: cmdemo-secrets
type: Opaque
data:
    CONTAINER_NAME :  dGVzdAo=
    ACCOUNT_KEY:  RWpFaC9lcjVZbEJSZVlpU3pWU0pWY2ViVXBORHZkOExrRkZCNXRZT0JKQnhZRmdES1JlZ3hqSnpzOFJzRWdjaTVScmxnRG51dmsxK2NTTXZFZEtIQXc9PQo=
    ACCOUNT_NAME:  ZnJkZW1vCg==
    SP_NAME:  aHR0cDovL3Z1Z2dpZW9wZW5zaGlmdGRlbW8K
    SP_PASSWORD:  SGVsbG9Xb3JsZDEyMyEK
    SP_TENANT:  NzJmOTg4YmYtODZmMS00MWFmLTkxYWItMmQ3Y2QwMTFkYjQ3Cg==
